"""add job pricing and location

Revision ID: c42b5942fff2
Revises: 4a083a03da05
Create Date: 2026-02-04 16:28:17.348934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c42b5942fff2'
down_revision: Union[str, Sequence[str], None] = '4a083a03da05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_profiles_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.add_column('jobs', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('location_address', sa.String(), nullable=True))
    op.add_column('worker_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('worker_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'longitude')
    op.drop_column('worker_profiles', 'latitude')
    op.drop_column('jobs', 'location_address')
    op.drop_column('jobs', 'longitude')
    op.drop_column('jobs', 'latitude')
    op.drop_column('jobs', 'price')
    op.create_table('client_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('client_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('client_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_client_profiles_id'), 'client_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
